export default {
  ID: 'zh-CN',
  name: 'zh-hans',
  /**
   * @version 2.15.14
   */
  el: {
    colorpicker: {
      confirm: '确定',
      clear: '清空',
    },
    datepicker: {
      now: '此刻',
      today: '今天',
      cancel: '取消',
      clear: '清空',
      confirm: '确定',
      selectDate: '选择日期',
      selectTime: '选择时间',
      startDate: '开始日期',
      startTime: '开始时间',
      endDate: '结束日期',
      endTime: '结束时间',
      prevYear: '前一年',
      nextYear: '后一年',
      prevMonth: '上个月',
      nextMonth: '下个月',
      year: '年',
      month1: '1 月',
      month2: '2 月',
      month3: '3 月',
      month4: '4 月',
      month5: '5 月',
      month6: '6 月',
      month7: '7 月',
      month8: '8 月',
      month9: '9 月',
      month10: '10 月',
      month11: '11 月',
      month12: '12 月',
      // week: '周次',
      weeks: {
        sun: '日',
        mon: '一',
        tue: '二',
        wed: '三',
        thu: '四',
        fri: '五',
        sat: '六',
      },
      months: {
        jan: '一月',
        feb: '二月',
        mar: '三月',
        apr: '四月',
        may: '五月',
        jun: '六月',
        jul: '七月',
        aug: '八月',
        sep: '九月',
        oct: '十月',
        nov: '十一月',
        dec: '十二月',
      },
    },
    select: {
      loading: '加载中',
      noMatch: '无匹配数据',
      noData: '无数据',
      placeholder: '请选择',
    },
    cascader: {
      noMatch: '无匹配数据',
      loading: '加载中',
      placeholder: '请选择',
      noData: '暂无数据',
    },
    pagination: {
      goto: '前往',
      pagesize: '条/页',
      total: '共 {total} 条',
      pageClassifier: '页',
    },
    messagebox: {
      title: '提示',
      confirm: '确定',
      cancel: '取消',
      error: '输入的数据不合法!',
    },
    upload: {
      deleteTip: '按 delete 键可删除',
      delete: '删除',
      preview: '查看图片',
      continue: '继续上传',
    },
    table: {
      emptyText: '暂无数据',
      confirmFilter: '筛选',
      resetFilter: '重置',
      clearFilter: '全部',
      sumText: '合计',
    },
    tree: {
      emptyText: '暂无数据',
    },
    transfer: {
      noMatch: '无匹配数据',
      noData: '无数据',
      titles: ['列表 1', '列表 2'],
      filterPlaceholder: '请输入搜索内容',
      noCheckedFormat: '共 {total} 项',
      hasCheckedFormat: '已选 {checked}/{total} 项',
    },
    image: {
      error: '加载失败',
    },
    pageHeader: {
      title: '返回',
    },
    popconfirm: {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
    },
    empty: {
      description: '暂无数据',
    },
  },

  lang: {
    // 基础区
    pageTitle: '切片浏览',
    yes: '确定',
    cancel: '取消',
    save: '保存',
    add: '添加',
    edit: '编辑',
    delete: '删除',
    close: '关闭',
    open: '开启',
    off: '关闭',
    on: '开启',
    clean: '清除',
    move: '移动',
    title: '标题',
    content: '内容',
    saving: '正在保存...',
    successAdd: '添加成功！',
    successEdit: '修改成功！',
    successSave: '保存成功！',
    successDelete: '删除成功！',
    loadingText: '切片加载中...',
    downloading: '正在下载...',
    waiting: '初始化未完成，请稍后再试...',
    colon: '：',
    // 功能区
    openSidebar: '打开侧边栏',
    closeSidebar: '缩小侧边栏',
    userSet: '用户自定义',
    showSet: '功能显示设置',
    readSet: '阅片偏好设置',
    cutSet: '截图预设',
    cutType: '默认截图模式',
    cutSize: '默认截图尺寸',
    qpInfo: '切片信息',
    caseInfo: '病例信息',
    touchMode: '触屏模式',
    fontBig: '大',
    fontSmall: '小',
    fullPage: '全屏',
    export: '导出切片',
    isExporting: '正在导出切片文件...',
    allQps: '切片列表',
    screenshots: '截图',
    quitFullScreen: 'Esc退出全屏',
    noSupport: '您的浏览器不支持此功能，请按F11进入全屏',
    noSupport2: '您的浏览器不支持此功能，请按F11或ESC退出全屏',
    slideName: '切片名称',
    slideSize: '切片大小',
    imagePixel: '图像像素',
    scanRate: '扫描倍率',
    resolution: '分辨率',
    touchOff: '触屏已关闭',
    touchOn: '触屏已启用',
    touchNoticeTitle: '触屏识别提示',
    touchNoticeContent: '您的浏览器当前为触屏模式，可在右上角点击“触屏按钮”关闭。',
    wrongAddress: '访问地址无效',
    cutDes: '截图描述',
    cutReq: '请输入200字以内截图描述。',
    wrongCut: '截图描述不能超过200字！',
    annotation: '标注',
    anoShape: '标注形状',
    anoColor: '标注颜色',
    anoList: '标注列表',
    expertAno: '导出标注',
    noAnnotation: '该切片暂无标注！',
    imgAdjust: '图像调节',
    gamma: '伽马',
    contrast: '对比度',
    bright: '亮度',
    rgb: '颜色通道',
    red: '红',
    green: '绿',
    blue: '蓝',
    kis: '锐化',
    // reset: '复位',
    all: '全部',
    otherFunc: '更多功能',
    noticeSliceDeepTitle: '提示',
    noticeSliceDeep: '您当前访问的切片需要激活，请在5分钟后刷新查看！',
    noticeEditAno: '标注编辑尚未完成，请勿进行其他操作！', // annotation.js
    noticeSizeAno: '标注范围太小，请重新绘制！',
    // noticeSizeAno2: '曲线范围太小，请重新绘制！',
    editPoint: '编辑点',
    movePoint: '移动点',
    closePoint: '关闭点',
    dragBar: '拖动工具栏',
    manual: '使用说明',
    backStep: '回退上一步',
    titleReq: '请输入20字以内标注标题',
    contentReq: '请输入100字以内标注内容',
    editAno: '标注信息',
    color: '颜色',
    titleWarn: '标题长度不能超过20字！',
    contentWarn: '内容长度不能超过100字！',
    noTitle: '无标题',
    length2: '长度',
    width2: '水平直径',
    height2: '垂直直径',
    area2: '面积',
    failLoadAnoList: '加载标注内容失败,请重试！',
    saveWarn: '曲线绘制完成后才能保存！',
    noticeMeasure: '再次点击“测量”按钮退出测量模式！',
    warnMeasure: '测量时无法做其他操作，需要再次点击“测量”按钮退出测量模式！',
    nav: '导航图',
    markNav: '标注导航',
    sizeRuler: '比例尺',
    rateRuler: '倍数尺',
    arrowMove: '方向键',
    label: '标签图',
    circle: '圆形',
    rect: '矩形',
    polygon: '自由笔',
    flag: '坐标',
    ellipse: '椭圆',
    lines: '测量',
    line: '线段',
    curve: '曲线',
    arrow: '箭头',
    radio: '录音',
    editPolygon: '编辑自由笔',
    square: '正方形',
    anoRed: '红色',
    anoLime: '绿色',
    anoDarkBlue: '深蓝',
    anoYellow: '黄色',
    anoPurple: '紫色',
    anoOrange: '橙色',
    anoLightBlue: '浅蓝',
    reachBounds: '您选择的播放方向已到边界',
    playStopped: '到达边界，播放已停止',
    play: '播放',
    pause: '停止',
    preview: '预览',
    timingClosure: '定时关闭',
    keepOpen: '保持开启',
    cutPart: '截取局部',
    fullCut: '截取全屏',
    oneKeyCut: '一键截图',
    startSplit: '打开分屏浏览',
    splitNotice: '请选择2-4张切片进行分屏浏览',
    splitNotice1: '请选择',
    splitNotice2: '张切片进行分屏浏览',
    splitNotice3: '相关切片少于',
    splitNotice4: '张，不支持分屏浏览！',
    rangeDblClick: '双击跳转区域',
    numKeyMove: '键盘位移距离',
    numKeyTime: '键盘位移速度',
    numZoomTime: '倍速切换速度',
    numAutoPlay: '自动播放速度',
    backTo: '回到原位',
    navSize: '导航图尺寸',
    autoPlayDirection: '播放默认方向',
    // 分屏浏览
    splitScreen: '分屏浏览',
    lockSlide: '切片锁定',
    // AI专用
    auxiliaryDiagnosis: '辅助诊断',
    prostateDiagnosis: '辅助诊断',
    lakeWM: '阅片诊断',
    aiAnalysis: 'AI诊断',
    pathologistDiagnosis: '人工诊断',
    positive: '阳性',
    negative: '阴性',
    gleasonScore: 'Gleason评分',
    reset: '清除',
    submit: '提交',
    detectedArea: '可疑区域',
    originPic: '原图',
    subSuccessfully: '提交成功',
    aipLoading: '前列腺诊断数据加载中...',
    // lake待翻译
    lakeQD: '审核', // 千岛湖title
    // 无权限页面
    noAuthMsg: '抱歉，您没有权限访问...',
    noLoginMsg: '抱歉，您还没有登录...',
    noSelectMsg: '您未选择要浏览的切片',
    quickLogin: '立即登录',
    noLogin: '未登录',
    noAuth: '无权限',
    noSelect: '未选择',
    // 扫码浏览
    qrCode: '扫码浏览',
    qrCodeOpen: '公开分享',
    qrCodeOutside: '站外分享',
    qrCodeOnside: '站内协作',
    qrCodeDes: '扫码用户无需登录，即可浏览切片。',
    qrCodeDes1: '扫码用户需登录后访问此切片，并可协同操作。',
    qrCodeNotice: '请勿将此二维码分享给其他人',
    // 标注改版
    colorPicker: '取色器',
    mutipleMode: '多次标注',
    colorChoose: '自定义',
    exportAnoList: '导出',
    importAnoList: '导入',
    importAnoList2: '导入标注',
    importSuccess: '导入成功！',
    importError: '导入失败！',
    anoRemark: '备注',
    anoTypeUpdate: '类型',
    squareSize: '正方形尺寸',
    anoCategory: '标注类型',
    all2: '全部',
    noticeSizeAno2: '在当前倍率，您绘制的相对尺寸太小！',
    noticeSizeAno3: '请输入10-100000之间的正方形边长！',
    chooseFile: '点击上传',
    fileLimit: '只能上传 ndpa、xml、xls、xlsx 文件，且不超过500KB',
    noAno: '暂无可导出的标注！',
    // 切片列表
    prev: '上一张',
    next: '下一张',
    // 镜下所见
    hpf: '镜下所见',
    hpfShowStatus: '视野状态',
    hpfShowShape: '视野形状',
    hpfShowDiameter: '视野直径',
    hpfCircle: '圆形',
    hpfRect: '矩形',
    hpfWarnEmpty: '请输入数字!',
    hpfWarnRange: '支持的视野设定范围在0.1-2！',
    hpfWarnDecimalPlace: '小数点后最多保留三位！',
  },
} as const;
