<template>
  <!--
    Generated by scripts/gen-el-icon.js
    DON'T EDIT THIS!!!
  -->
  <svg
    width="1em"
    height="1em"
    fill="currentColor"
    aria-label="briefcase"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 1024 1024"
  >
    <path
      fill="currentColor"
      d="M320 320V128h384v192h192v192H128V320zM128 576h768v320H128zm256-256h256.064V192H384z"
    />
  </svg>
</template>
