<template>
  <!--
    Generated by scripts/gen-el-icon.js
    DON'T EDIT THIS!!!
  -->
  <svg
    width="1em"
    height="1em"
    fill="currentColor"
    aria-label="home-filled"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 1024 1024"
  >
    <path
      fill="currentColor"
      d="M512 128 128 447.936V896h255.936V640H640v256h255.936V447.936z"
    />
  </svg>
</template>
