<template>
  <!--
    Generated by scripts/gen-el-icon.js
    DON'T EDIT THIS!!!
  -->
  <svg
    width="1em"
    height="1em"
    fill="currentColor"
    aria-label="platform"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 1024 1024"
  >
    <path
      fill="currentColor"
      d="M448 832v-64h128v64h192v64H256v-64zM128 704V128h768v576z"
    />
  </svg>
</template>
