// Generated by scripts/gen-el-ui.js
// Date: 2024-06-24 23:38:18
// DON'T EDIT THIS!!!

import type { VueConstructor, PluginFunction } from 'vue';

// Components
import { ElAutoResizer } from './auto-resizer';
import { ElClose } from './close';
import { ElIcon } from './icon';

const components = [
  ElAutoResizer,
  ElClose,
  ElIcon,
];

const plugins = [

] as PluginFunction<any>[];

let isInstalled = false;
export default function install(Vue: VueConstructor) {
  if (isInstalled) return;
  isInstalled = true;

  components.forEach(c => Vue.component(c.name!, c));
  plugins.forEach(p => Vue.use(p));
}
