// Generated by scripts/gen-el-ui.js
// Date: 2024-06-24 23:38:18
// DON'T EDIT THIS!!!

export {};

// Read more: https://github.com/vuejs/core/pull/3399
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('./alert')['ElAlert'];
    ElAutoResizer: typeof import('./auto-resizer')['ElAutoResizer'];
    ElBadge: typeof import('./badge')['ElBadge'];
    ElButton: typeof import('./button')['ElButton'];
    ElButtonGroup: typeof import('./button')['ElButtonGroup'];
    ElCard: typeof import('./card')['ElCard'];
    ElCheckbox: typeof import('./checkbox')['ElCheckbox'];
    ElCheckboxGroup: typeof import('./checkbox')['ElCheckboxGroup'];
    ElClose: typeof import('./close')['ElClose'];
    ElCollapseTransition: typeof import('./collapse-transition')['ElCollapseTransition'];
    ElDatePicker: typeof import('./date-picker')['ElDatePicker'];
    ElDialog: typeof import('./dialog')['ElDialog'];
    ElDrawer: typeof import('./drawer')['ElDrawer'];
    ElDropdown: typeof import('./dropdown')['ElDropdown'];
    ElDropdownItem: typeof import('./dropdown')['ElDropdownItem'];
    ElDropdownMenu: typeof import('./dropdown')['ElDropdownMenu'];
    ElForm: typeof import('./form')['ElForm'];
    ElFormItem: typeof import('./form')['ElFormItem'];
    ElIcon: typeof import('./icon')['ElIcon'];
    ElImage: typeof import('./image')['ElImage'];
    ElImageViewer: typeof import('./image-viewer')['ElImageViewer'];
    ElInput: typeof import('./input')['ElInput'];
    ElInputNumber: typeof import('./input-number')['ElInputNumber'];
    ElRow: typeof import('./layout')['ElRow'];
    ElCol: typeof import('./layout')['ElCol'];
    ElPagination: typeof import('./pagination')['ElPagination'];
    ElPopover: typeof import('./popover')['ElPopover'];
    ElProgress: typeof import('./progress')['ElProgress'];
    ElRadio: typeof import('./radio')['ElRadio'];
    ElRadioGroup: typeof import('./radio')['ElRadioGroup'];
    ElScrollbar: typeof import('./scrollbar')['ElScrollbar'];
    ElSelect: typeof import('./select')['ElSelect'];
    ElOption: typeof import('./select')['ElOption'];
    ElOptionGroup: typeof import('./select')['ElOptionGroup'];
    ElSlider: typeof import('./slider')['ElSlider'];
    ElSwitch: typeof import('./switch')['ElSwitch'];
    ElTable: typeof import('./table')['ElTable'];
    ElTableColumn: typeof import('./table')['ElTableColumn'];
    ElTabs: typeof import('./tabs')['ElTabs'];
    ElTabPane: typeof import('./tabs')['ElTabPane'];
    ElTag: typeof import('./tag')['ElTag'];
    ElTimePicker: typeof import('./time-picker')['ElTimePicker'];
    ElTooltip: typeof import('./tooltip')['ElTooltip'];
    ElTour: typeof import('./tour')['ElTour'];
    ElTourStep: typeof import('./tour')['ElTourStep'];
    ElTree: typeof import('./tree')['ElTree'];
    ElTreeSelect: typeof import('./tree-select')['ElTreeSelect'];
    ElUpload: typeof import('./upload')['ElUpload'];
    ['el-alert']: typeof import('./alert')['ElAlert'];
    ['el-auto-resizer']: typeof import('./auto-resizer')['ElAutoResizer'];
    ['el-badge']: typeof import('./badge')['ElBadge'];
    ['el-button']: typeof import('./button')['ElButton'];
    ['el-button-group']: typeof import('./button')['ElButtonGroup'];
    ['el-card']: typeof import('./card')['ElCard'];
    ['el-checkbox']: typeof import('./checkbox')['ElCheckbox'];
    ['el-checkbox-group']: typeof import('./checkbox')['ElCheckboxGroup'];
    ['el-close']: typeof import('./close')['ElClose'];
    ['el-collapse-transition']: typeof import('./collapse-transition')['ElCollapseTransition'];
    ['el-date-picker']: typeof import('./date-picker')['ElDatePicker'];
    ['el-dialog']: typeof import('./dialog')['ElDialog'];
    ['el-drawer']: typeof import('./drawer')['ElDrawer'];
    ['el-dropdown']: typeof import('./dropdown')['ElDropdown'];
    ['el-dropdown-item']: typeof import('./dropdown')['ElDropdownItem'];
    ['el-dropdown-menu']: typeof import('./dropdown')['ElDropdownMenu'];
    ['el-form']: typeof import('./form')['ElForm'];
    ['el-form-item']: typeof import('./form')['ElFormItem'];
    ['el-icon']: typeof import('./icon')['ElIcon'];
    ['el-image']: typeof import('./image')['ElImage'];
    ['el-image-viewer']: typeof import('./image-viewer')['ElImageViewer'];
    ['el-input']: typeof import('./input')['ElInput'];
    ['el-input-number']: typeof import('./input-number')['ElInputNumber'];
    ['el-row']: typeof import('./layout')['ElRow'];
    ['el-col']: typeof import('./layout')['ElCol'];
    ['el-pagination']: typeof import('./pagination')['ElPagination'];
    ['el-popover']: typeof import('./popover')['ElPopover'];
    ['el-progress']: typeof import('./progress')['ElProgress'];
    ['el-radio']: typeof import('./radio')['ElRadio'];
    ['el-radio-group']: typeof import('./radio')['ElRadioGroup'];
    ['el-scrollbar']: typeof import('./scrollbar')['ElScrollbar'];
    ['el-select']: typeof import('./select')['ElSelect'];
    ['el-option']: typeof import('./select')['ElOption'];
    ['el-option-group']: typeof import('./select')['ElOptionGroup'];
    ['el-slider']: typeof import('./slider')['ElSlider'];
    ['el-switch']: typeof import('./switch')['ElSwitch'];
    ['el-table']: typeof import('./table')['ElTable'];
    ['el-table-column']: typeof import('./table')['ElTableColumn'];
    ['el-tabs']: typeof import('./tabs')['ElTabs'];
    ['el-tab-pane']: typeof import('./tabs')['ElTabPane'];
    ['el-tag']: typeof import('./tag')['ElTag'];
    ['el-time-picker']: typeof import('./time-picker')['ElTimePicker'];
    ['el-tooltip']: typeof import('./tooltip')['ElTooltip'];
    ['el-tour']: typeof import('./tour')['ElTour'];
    ['el-tour-step']: typeof import('./tour')['ElTourStep'];
    ['el-tree']: typeof import('./tree')['ElTree'];
    ['el-tree-select']: typeof import('./tree-select')['ElTreeSelect'];
    ['el-upload']: typeof import('./upload')['ElUpload'];
  }

  interface ComponentCustomProperties {
    $loading: typeof import('./loading')['ElLoadingService'];
    $message: typeof import('./message')['ElMessage'];
    $messageBox: typeof import('./message-box')['ElMessageBox'];
    $alert: typeof import('./message-box')['ElMessageBox']['alert'];
    $prompt: typeof import('./message-box')['ElMessageBox']['prompt'];
    $confirm: typeof import('./message-box')['ElMessageBox']['confirm'];
    $notify: typeof import('./notification')['ElNotification'];
  }
}
